{"links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784/comments/95962374.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784/_/diff#comment-95962374"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}, "content": {"raw": "I will test this with the ign-physics 1.1.0~pre1 prerelease. ign-physics has protected branches, so I expect to need to modify the branch permissions to make this release", "markup": "markdown", "html": "<p>I will test this with the ign-physics 1.1.0~pre1 prerelease. ign-physics has protected branches, so I expect to need to modify the branch permissions to make this release</p>", "type": "rendered"}, "created_on": "2019-03-21T21:57:21.508252+00:00", "user": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "updated_on": "2019-03-21T21:57:21.520806+00:00", "type": "pullrequest_comment", "id": 95962374}