{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "links": {"attachments": {"href": "data/repositories/osrf/release-tools/issues/151/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/release-tools/issues/151.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/release-tools/issues/151/watch"}, "comments": {"href": "data/repositories/osrf/release-tools/issues/151/comments_page=1.json"}, "html": {"href": "#!/osrf/release-tools/issues/151/releasepy-doesnt-catch-hg-tag-hg-push"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/release-tools/issues/151/vote"}}, "reporter": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "title": "release.py doesn't catch `hg tag`, `hg push` errors", "component": {"name": "release", "links": {"self": {"href": "data/repositories/osrf/release-tools/components/399532.json"}}}, "votes": 0, "watches": 1, "content": {"raw": "I recently tried to make a release to a protected branch, and `hg push` failed, but the `release.py` script didn't detect the failure; it just kept going. I believe it's due to this logic:\r\n\r\n* #!/osrf/release-tools/src/03d41f12caa248d6747c656e1324474b3d75c008/release.py?at=default&fileviewer=file-view-default#release.py-401:409\r\n\r\nIs there a better way to detect git, so we don't ignore valid mercurial failures?\r\n\r\ncc @\\_jrivero_ @chapulina @nkoenig", "markup": "markdown", "html": "<p>I recently tried to make a release to a protected branch, and <code>hg push</code> failed, but the <code>release.py</code> script didn't detect the failure; it just kept going. I believe it's due to this logic:</p>\n<ul>\n<li><a href=\"#!/osrf/release-tools/src/03d41f12caa248d6747c656e1324474b3d75c008/release.py?at=default&amp;fileviewer=file-view-default#release.py-401:409\" rel=\"nofollow\" class=\"ap-connect-link\">#!/osrf/release-tools/src/03d41f12caa248d6747c656e1324474b3d75c008/release.py?at=default&amp;fileviewer=file-view-default#release.py-401:409</a></li>\n</ul>\n<p>Is there a better way to detect git, so we don't ignore valid mercurial failures?</p>\n<p>cc @_jrivero_ @chapulina @nkoenig</p>", "type": "rendered"}, "assignee": {"display_name": "Jose Luis Rivero", "uuid": "{d12309b2-f745-42ee-b119-aec4fcdf81fe}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D"}, "html": {"href": "https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/109284c8b83411dbc7492138f6167e9ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJR-5.png"}}, "nickname": "Jose Luis Rivero", "type": "user", "account_id": "557058:155a32e2-420c-4d50-98e0-0e722f63f906"}, "state": "resolved", "version": null, "edited_on": null, "created_on": "2019-03-15T18:02:44.249431+00:00", "milestone": null, "updated_on": "2019-04-09T18:47:21.378311+00:00", "type": "issue", "id": 151}