{"pagelen": 50, "values": [{"update": {"description": "Should fix issue #151.\r\n\r\nWe should try it in some real calls before merging since it is not trivial to simulate the whole stack of calls. I\u2019ve tried it with a reduced set of code in release.py but not with the whole script.", "title": "Return custom errors from problems in hg calls during release.py runs", "destination": {"commit": {"hash": "0bdfb0018d7b", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/release-tools/commit/0bdfb0018d7b.json"}, "html": {"href": "#!/osrf/release-tools/commits/0bdfb0018d7b"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "branch": {"name": "default"}}, "reason": "", "source": {"commit": {"hash": "383dee1bc2b9", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/release-tools/commit/383dee1bc2b9.json"}, "html": {"href": "#!/osrf/release-tools/commits/383dee1bc2b9"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "branch": {"name": "improve_error"}}, "state": "MERGED", "author": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "date": "2019-04-09T18:47:01.196594+00:00"}, "pull_request": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}}, {"approval": {"date": "2019-04-09T18:45:40.501940+00:00", "pullrequest": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}, "user": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}}, "pull_request": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}}, {"comment": {"links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784/comments/96666079.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784/_/diff#comment-96666079"}}, "parent": {"id": 96483725, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784/comments/96483725.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784/_/diff#comment-96483725"}}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}, "content": {"raw": "we don\u2019t have too many, ariac is one of the few examples [https://bitbucket.org/osrf/ariac](https://bitbucket.org/osrf/ariac/src/master/)", "markup": "markdown", "html": "<p>we don\u2019t have too many, ariac is one of the few examples <a data-is-external-link=\"true\" href=\"https://bitbucket.org/osrf/ariac/src/master/\" rel=\"nofollow\">https://bitbucket.org/osrf/ariac</a></p>", "type": "rendered"}, "created_on": "2019-03-27T23:05:55.887166+00:00", "user": {"display_name": "Jose Luis Rivero", "uuid": "{d12309b2-f745-42ee-b119-aec4fcdf81fe}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D"}, "html": {"href": "https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/109284c8b83411dbc7492138f6167e9ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJR-5.png"}}, "nickname": "Jose Luis Rivero", "type": "user", "account_id": "557058:155a32e2-420c-4d50-98e0-0e722f63f906"}, "updated_on": "2019-03-27T23:05:55.895001+00:00", "type": "pullrequest_comment", "id": 96666079}, "pull_request": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}}, {"comment": {"links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784/comments/96483725.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784/_/diff#comment-96483725"}}, "parent": {"id": 96481354, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784/comments/96481354.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784/_/diff#comment-96481354"}}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}, "content": {"raw": "do you have an example of a git repo for which the release.py script is used? I'm just curious why we have it", "markup": "markdown", "html": "<p>do you have an example of a git repo for which the release.py script is used? I'm just curious why we have it</p>", "type": "rendered"}, "created_on": "2019-03-26T22:34:29.647401+00:00", "user": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "updated_on": "2019-03-26T22:34:29.654923+00:00", "type": "pullrequest_comment", "id": 96483725}, "pull_request": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}}, {"update": {"description": "Should fix issue #151.\r\n\r\nWe should try it in some real calls before merging since it is not trivial to simulate the whole stack of calls. I\u2019ve tried it with a reduced set of code in release.py but not with the whole script.", "title": "Return custom errors from problems in hg calls during release.py runs", "destination": {"commit": {"hash": "c66a45a13e16", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/release-tools/commit/c66a45a13e16.json"}, "html": {"href": "#!/osrf/release-tools/commits/c66a45a13e16"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "branch": {"name": "default"}}, "reason": "", "source": {"commit": {"hash": "383dee1bc2b9", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/release-tools/commit/383dee1bc2b9.json"}, "html": {"href": "#!/osrf/release-tools/commits/383dee1bc2b9"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "branch": {"name": "improve_error"}}, "state": "OPEN", "author": {"display_name": "Jose Luis Rivero", "uuid": "{d12309b2-f745-42ee-b119-aec4fcdf81fe}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D"}, "html": {"href": "https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/109284c8b83411dbc7492138f6167e9ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJR-5.png"}}, "nickname": "Jose Luis Rivero", "type": "user", "account_id": "557058:155a32e2-420c-4d50-98e0-0e722f63f906"}, "date": "2019-03-26T22:09:24.694219+00:00"}, "pull_request": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}}, {"update": {"description": "Should fix issue #151.\r\n\r\nWe should try it in some real calls before merging since it is not trivial to simulate the whole stack of calls. I\u2019ve tried it with a reduced set of code in release.py but not with the whole script.", "title": "Return custom errors from problems in hg calls during release.py runs", "destination": {"commit": {"hash": "c66a45a13e16", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/release-tools/commit/c66a45a13e16.json"}, "html": {"href": "#!/osrf/release-tools/commits/c66a45a13e16"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "branch": {"name": "default"}}, "reason": "", "source": {"commit": {"hash": "383dee1bc2b9", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/release-tools/commit/383dee1bc2b9.json"}, "html": {"href": "#!/osrf/release-tools/commits/383dee1bc2b9"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "branch": {"name": "improve_error"}}, "state": "OPEN", "author": {"display_name": "Jose Luis Rivero", "uuid": "{d12309b2-f745-42ee-b119-aec4fcdf81fe}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D"}, "html": {"href": "https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/109284c8b83411dbc7492138f6167e9ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJR-5.png"}}, "nickname": "Jose Luis Rivero", "type": "user", "account_id": "557058:155a32e2-420c-4d50-98e0-0e722f63f906"}, "date": "2019-03-26T22:09:23.898245+00:00"}, "pull_request": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}}, {"comment": {"links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784/comments/96481354.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784/_/diff#comment-96481354"}}, "parent": {"id": 95964561, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784/comments/95964561.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784/_/diff#comment-95964561"}}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}, "content": {"raw": "I remember to have tested it by using a subset of the code \\(not the whole script\\) and running it on top of an empty git repo in /tmp.", "markup": "markdown", "html": "<p>I remember to have tested it by using a subset of the code (not the whole script) and running it on top of an empty git repo in /tmp.</p>", "type": "rendered"}, "created_on": "2019-03-26T22:04:06.729138+00:00", "user": {"display_name": "Jose Luis Rivero", "uuid": "{d12309b2-f745-42ee-b119-aec4fcdf81fe}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D"}, "html": {"href": "https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/109284c8b83411dbc7492138f6167e9ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJR-5.png"}}, "nickname": "Jose Luis Rivero", "type": "user", "account_id": "557058:155a32e2-420c-4d50-98e0-0e722f63f906"}, "updated_on": "2019-03-26T22:04:06.739314+00:00", "type": "pullrequest_comment", "id": 96481354}, "pull_request": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}}, {"comment": {"links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784/comments/95964561.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784/_/diff#comment-95964561"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}, "content": {"raw": "how do we test `ErrorGitRepo`?", "markup": "markdown", "html": "<p>how do we test <code>ErrorGitRepo</code>?</p>", "type": "rendered"}, "created_on": "2019-03-21T22:25:48.397723+00:00", "user": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "updated_on": "2019-03-21T22:25:48.405314+00:00", "type": "pullrequest_comment", "id": 95964561}, "pull_request": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}}, {"comment": {"links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784/comments/95964281.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784/_/diff#comment-95964281"}}, "parent": {"id": 95962374, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784/comments/95962374.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784/_/diff#comment-95962374"}}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}, "content": {"raw": "It worked properly, terminating the script when `hg push` failed. It had already uploaded a tarball, but I think that's ok", "markup": "markdown", "html": "<p>It worked properly, terminating the script when <code>hg push</code> failed. It had already uploaded a tarball, but I think that's ok</p>", "type": "rendered"}, "created_on": "2019-03-21T22:21:45.531552+00:00", "user": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "updated_on": "2019-03-21T22:21:45.543202+00:00", "type": "pullrequest_comment", "id": 95964281}, "pull_request": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}}, {"comment": {"links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784/comments/95962504.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784/_/diff#comment-95962504"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}, "content": {"raw": "`if you have` -> `if you do not have` I think", "markup": "markdown", "html": "<p><code>if you have</code> -&gt; <code>if you do not have</code> I think</p>", "type": "rendered"}, "created_on": "2019-03-21T21:59:12.657080+00:00", "user": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "inline": {}, "updated_on": "2019-03-21T21:59:12.665215+00:00", "type": "pullrequest_comment", "id": 95962504}, "pull_request": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}}, {"comment": {"links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784/comments/95962374.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784/_/diff#comment-95962374"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}, "content": {"raw": "I will test this with the ign-physics 1.1.0~pre1 prerelease. ign-physics has protected branches, so I expect to need to modify the branch permissions to make this release", "markup": "markdown", "html": "<p>I will test this with the ign-physics 1.1.0~pre1 prerelease. ign-physics has protected branches, so I expect to need to modify the branch permissions to make this release</p>", "type": "rendered"}, "created_on": "2019-03-21T21:57:21.508252+00:00", "user": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "updated_on": "2019-03-21T21:57:21.520806+00:00", "type": "pullrequest_comment", "id": 95962374}, "pull_request": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}}, {"update": {"description": "Should fix issue #151.\r\n\r\nWe should try it in some real calls before merging since it is not trivial to simulate the whole stack of calls. I\u2019ve tried it with a reduced set of code in release.py but not with the whole script.", "title": "Return custom errors from problems in hg calls during release.py runs", "destination": {"commit": {"hash": "0094c09b5f43", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/release-tools/commit/0094c09b5f43.json"}, "html": {"href": "#!/osrf/release-tools/commits/0094c09b5f43"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "branch": {"name": "default"}}, "reason": "", "source": {"commit": {"hash": "3d72d72c4a5a", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/release-tools/commit/3d72d72c4a5a.json"}, "html": {"href": "#!/osrf/release-tools/commits/3d72d72c4a5a"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "branch": {"name": "improve_error"}}, "state": "OPEN", "author": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "date": "2019-03-18T17:17:20.658380+00:00"}, "pull_request": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}}, {"update": {"description": "Should fix issue #151.\r\n\r\nWe should try it in some real calls before merging since it is not trivial to simulate the whole stack of calls. I\u2019ve tried it with a reduced set of code in release.py but not with the whole script.", "title": "Return custom errors from problems in hg calls during release.py runs", "destination": {"commit": {"hash": "0094c09b5f43", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/release-tools/commit/0094c09b5f43.json"}, "html": {"href": "#!/osrf/release-tools/commits/0094c09b5f43"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "branch": {"name": "default"}}, "reason": "", "source": {"commit": {"hash": "3d72d72c4a5a", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/release-tools/commit/3d72d72c4a5a.json"}, "html": {"href": "#!/osrf/release-tools/commits/3d72d72c4a5a"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "branch": {"name": "improve_error"}}, "state": "OPEN", "author": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "date": "2019-03-18T17:17:19.599375+00:00"}, "pull_request": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}}, {"update": {"description": "Should fix issue #151.\r\n\r\nWe should try it in some real calls before merging since it is not trivial to simulate the whole stack of calls. I\u2019ve tried it with a reduced set of code in release.py but not with the whole script.", "title": "Return custom errors from problems in hg calls during release.py runs", "destination": {"commit": {"hash": "03d41f12caa2", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/release-tools/commit/03d41f12caa2.json"}, "html": {"href": "#!/osrf/release-tools/commits/03d41f12caa2"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "branch": {"name": "default"}}, "reason": "", "source": {"commit": {"hash": "3889129e54a5", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/release-tools/commit/3889129e54a5.json"}, "html": {"href": "#!/osrf/release-tools/commits/3889129e54a5"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "branch": {"name": "improve_error"}}, "state": "OPEN", "author": {"display_name": "Jose Luis Rivero", "uuid": "{d12309b2-f745-42ee-b119-aec4fcdf81fe}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D"}, "html": {"href": "https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/109284c8b83411dbc7492138f6167e9ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJR-5.png"}}, "nickname": "Jose Luis Rivero", "type": "user", "account_id": "557058:155a32e2-420c-4d50-98e0-0e722f63f906"}, "date": "2019-03-18T15:58:05.050968+00:00"}, "pull_request": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}}, {"update": {"description": "Should fix issue #151.\r\n\r\nWe should try it in some real calls before merging since it is not trivial to simulate the whole stack of calls. I\u2019ve tried it with a reduced set of code in release.py but not with the whole script.", "title": "Return custom errors from problems in hg calls during release.py runs", "destination": {"commit": {"hash": "03d41f12caa2", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/release-tools/commit/03d41f12caa2.json"}, "html": {"href": "#!/osrf/release-tools/commits/03d41f12caa2"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "branch": {"name": "default"}}, "reason": "", "source": {"commit": {"hash": "3889129e54a5", "type": "commit", "links": {"self": {"href": "data/repositories/osrf/release-tools/commit/3889129e54a5.json"}, "html": {"href": "#!/osrf/release-tools/commits/3889129e54a5"}}}, "repository": {"links": {"self": {"href": "data/repositories/osrf/release-tools.json"}, "html": {"href": "#!/osrf/release-tools"}, "avatar": {"href": "data/bytebucket.org/ravatar/{41811d3d-19d0-428e-a134-976595e72508}ts=python"}}, "type": "repository", "name": "release-tools", "full_name": "osrf/release-tools", "uuid": "{41811d3d-19d0-428e-a134-976595e72508}"}, "branch": {"name": "improve_error"}}, "state": "OPEN", "author": {"display_name": "Jose Luis Rivero", "uuid": "{d12309b2-f745-42ee-b119-aec4fcdf81fe}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D"}, "html": {"href": "https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/109284c8b83411dbc7492138f6167e9ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJR-5.png"}}, "nickname": "Jose Luis Rivero", "type": "user", "account_id": "557058:155a32e2-420c-4d50-98e0-0e722f63f906"}, "date": "2019-03-18T15:58:04.986976+00:00"}, "pull_request": {"type": "pullrequest", "id": 784, "links": {"self": {"href": "data/repositories/osrf/release-tools/pullrequests/784.json"}, "html": {"href": "#!/osrf/release-tools/pull-requests/784"}}, "title": "Return custom errors from problems in hg calls during release.py runs"}}]}